const DogList = [
  {
    id: 0,
    gender: 'Female',
    name: 'Bella',
    breed: 'Chow',
    image: 'https://images.dog.ceo/breeds/chow/n02112137_3032.jpg',
    open: false,
  },
  {
    id: 1,
    gender: 'Female',
    name: 'Luna',
    breed: 'Ibizan Hound',
    image: 'https://images.dog.ceo/breeds/hound-ibizan/n02091244_2427.jpg',
    open: false,
  },
  {
    id: 2,
    gender: 'Female',
    name: 'Daisy',
    breed: 'Bouvier',
    image: 'https://images.dog.ceo/breeds/bouvier/n02106382_611.jpg',
    open: false,
  },
  {
    id: 3,
    gender: 'Male',
    name: 'Max',
    breed: 'Entlebucher',
    image: 'https://images.dog.ceo/breeds/entlebucher/n02108000_3207.jpg',
    open: false,
  },
  {
    id: 4,
    gender: 'Male',
    name: 'Milo',
    breed: 'Scottish Deerhound',
    image: 'https://images.dog.ceo/breeds/deerhound-scottish/n02092002_854.jpg',
    open: false,
  },
  {
    id: 5,
    gender: 'Female',
    name: 'Lucy',
    breed: 'Sussex Spaniel',
    image: 'https://images.dog.ceo/breeds/spaniel-sussex/n02102480_8269.jpg',
    open: false,
  },
  {
    id: 6,
    gender: 'Male',
    name: 'Cooper',
    breed: 'Pyrenees',
    image: 'https://images.dog.ceo/breeds/pyrenees/n02111500_6769.jpg',
    open: false,
  },
  {
    id: 7,
    gender: 'Male',
    name: 'Loki',
    breed: 'Eskimo',
    image: 'https://images.dog.ceo/breeds/eskimo/n02109961_2532.jpg',
    open: false,
  },
  {
    id: 8,
    gender: 'Female',
    name: 'Lily',
    breed: 'Akita',
    image: 'https://images.dog.ceo/breeds/akita/512px-Akita_inu.jpg',
    open: false,
  },
  {
    id: 9,
    gender: 'Female',
    name: 'Bailey',
    breed: 'Doberman',
    image: 'https://images.dog.ceo/breeds/doberman/n02107142_607.jpg',
    open: false,
  },
  {
    id: 10,
    gender: 'Female',
    name: 'Gracie',
    breed: 'Cockapoo',
    image: 'https://images.dog.ceo/breeds/cockapoo/gracie.jpg',
    open: false,
  },
];
export default DogList;
